<a href="https://colab.research.google.com/github/wordman2/GINN/blob/main/Colab_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GINN Teil 8

## Imports

## Multiple Choice

Welche der Aussagen ist wahr?



1.   Dropout führt zu Sparsity in den trainierten Modellgewichten (True)
2.   Beim Testen auf Validierungsdaten wird Droput mit umgekehrter Wahrscheinlichkeit p angewendet (False, no dropout applied during validation)
3. Je kleiner die Dropout-Wahrscheinlichkeit p, desto stärker der Regularisierungseffekt auf die Gewichte in den Layern (False, da bernoulli 1-p gezogen wird. Effekt ist umgekehrt)
4. Aussagen 1-3 sind nicht wahr





## PyTorch Dropout zu Fuß

Implementieren Sie den PyTorch Dropout zu Fuß und stellen Sie sicher, dass Ihre Ergebnisse mit denen von PyTorch identisch sind (hört sich wahrscheinlich erstmal einfacher an als es ist :)



Hinweis: PyTorch implementiert den sogenannten "Inverted Dropout" wie hier besschrieben: https://pytorch.org/docs/stable/generated/torch.nn.Dropout.html, bei dem auf Grund des korrigierten Erwartungswertes **keine** Anpassungen zur Inferenzzeit mehr nötig sind.

In [ ]:
#Ihr Code hier
from torch.nn import Dropout
import torch

torch.manual_seed(0)

m = Dropout(p=0.2)
input = torch.randn(20, 16)
output = m(input)

def Dropout_by_foot(tensor, p=0.2):
  p_matrix = torch.full_like(tensor, 1-p)
  bernoulli_draw = torch.bernoulli(p_matrix)
  output = (tensor*bernoulli_draw)*(1/(1-p)) # scaling
  return output

Dropout_by_foot(input) == output

tensor([[ True,  True,  True,  True, False,  True,  True,  True,  True,  True,
          True, False, False,  True,  True, False],
        [False, False, False,  True,  True, False,  True,  True, False,  True,
          True,  True, False,  True,  True, False],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         False,  True, False, False,  True,  True],
        [ True,  True, False,  True,  True,  True,  True, False,  True,  True,
          True,  True, False, False,  True,  True],
        [False,  True, False,  True, False,  True,  True,  True,  True, False,
         False, False,  True, False, False,  True],
        [ True,  True,  True,  True,  True, False, False,  True, False,  True,
          True, False,  True,  True,  True,  True],
        [ True,  True, False, False,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True],
        [ True,  True, False,  True,  True,  True,  True,  True,  True,  True,
    

In [ ]:
output

tensor([[-1.4073e+00, -1.4405e+00, -3.1322e-01, -0.0000e+00,  1.0609e+00,
          8.6501e-01, -3.9502e-01, -2.6440e+00,  4.0284e-01, -1.5792e+00,
          4.3748e-01,  3.8517e-01,  1.4980e-01,  1.5471e+00,  1.3960e+00,
         -3.0910e-01],
        [-1.6908e+00, -2.1199e+00,  7.0831e-01,  9.9189e-01,  7.4855e-01,
         -1.9439e+00, -4.2670e-01,  2.3163e+00,  9.3774e-01, -7.3187e-01,
         -2.1675e-01,  2.2935e-01,  0.0000e+00,  1.9829e+00,  0.0000e+00,
         -0.0000e+00],
        [-7.6698e-01,  3.9491e-02, -6.1585e-01,  3.1052e-01,  5.4962e-01,
          1.4051e-01,  8.0099e-01,  5.5145e-01, -1.2789e-01,  9.9055e-01,
         -3.6208e-01,  6.5634e-02,  6.5358e-01,  2.8778e+00, -1.8361e+00,
         -1.9834e+00],
        [-8.4136e-01,  1.0910e+00,  1.3192e+00,  2.2230e-01, -2.8792e-01,
         -4.8969e-01,  6.7912e-01, -4.9395e-01, -0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00, -0.0000e+00, -0.0000e+00,  0.0000e+00,
         -6.8941e-01],
        [-7.1156e-01

In [ ]:
Dropout_by_foot(input)

tensor([[-1.4073e+00, -1.4405e+00, -3.1322e-01, -5.4235e-01,  0.0000e+00,
          8.6501e-01, -0.0000e+00, -2.6440e+00,  4.0284e-01, -1.5792e+00,
          4.3748e-01,  0.0000e+00,  1.4980e-01,  1.5471e+00,  1.3960e+00,
         -3.0910e-01],
        [-0.0000e+00, -2.1199e+00,  7.0831e-01,  9.9189e-01,  7.4855e-01,
         -0.0000e+00, -4.2670e-01,  2.3163e+00,  0.0000e+00, -7.3187e-01,
         -0.0000e+00,  2.2935e-01,  0.0000e+00,  1.9829e+00,  1.1829e+00,
         -1.0546e+00],
        [-7.6698e-01,  3.9491e-02, -0.0000e+00,  3.1052e-01,  5.4962e-01,
          0.0000e+00,  8.0099e-01,  0.0000e+00, -1.2789e-01,  9.9055e-01,
         -3.6208e-01,  6.5634e-02,  0.0000e+00,  2.8778e+00, -1.8361e+00,
         -1.9834e+00],
        [-8.4136e-01,  1.0910e+00,  1.3192e+00,  0.0000e+00, -0.0000e+00,
         -4.8969e-01,  6.7912e-01, -0.0000e+00, -5.5777e-01,  9.3003e-01,
          1.9012e+00,  4.2631e+00, -1.9140e+00, -1.5427e+00,  2.2747e+00,
         -6.8941e-01],
        [-7.1156e-01

## Experiment mit Weights&Biases

Optional: Spielen Sie das Beispiel durch und notieren Sie Fragen und Erkenntnisse. Sie benötigen um das Beispiel sinnvoll nutzen zu können einen Weights&Biases Account - wenn Sie sich diesen nicht anlegen möchten ist das kein Problem, wir werden das Beispiel auch nochmal gemeinsam kurz durchgehen.


https://colab.research.google.com/github/wandb/examples/blob/master/colabs/pytorch/How_does_adding_dropout_affect_model_performance.ipynb
